### ISSUE TITLE
Images not being replaced

### ISSUE THREAD

**Issue by asdfuken** [senny/sablon#105]
Hello

I have a document where I try to replace an image without success. The sourcecode to add the image is:

```
      v.vulnerability_files.where("file_content_type LIKE 'image/%'").each_with_index do |img, ii|
        fname = "/tmp/image-#{SecureRandom.urlsafe_base64}." + img.file.original_filename.split(".")[-1]
        img.file.copy_to_local_file(:original, fname)
        media.push(Sablon.content(:image, fname))
      end
```

While the document structure is this:
<img width="511" alt="screen shot 2018-05-07 at 10 52 06 am" src="https://user-images.githubusercontent.com/1236942/39705532-192f4696-51e5-11e8-9203-b1f0b54c6331.png">

I hope we can find a solution.

Thank you

**Comment by stadelmanma** [comment]
Hi @asdfuken do you get any kind of error? Or is your placeholder image simply replicated for each item in your media array?

**Comment by asdfuken** [comment]
Hello, I have updated my code as following:

`
    @vulnerabilities.each_with_index do |v, i|
      data = {
..........
        'media': []
        }
      media = []
      v.files_blobs.where("content_type LIKE 'image/%'").each_with_index do |img, ii|
        fname = "/tmp/image-#{SecureRandom.urlsafe_base64}" 
        File.open(fname, 'wb') do |file|
           file.write(img.download)
        end     
        content = StringIO.new(IO.binread(fname))
        mediadata = Sablon.content(:image, content, filename: "#{SecureRandom.urlsafe_base64}.png")
        media.push({
          :image => mediadata,
          :caption => ""
          })
      end
      data[:media] = media
      vulnerabilities.push(data)
    end
......


    context = {
.......
      vulnerabilities: vulnerabilities,
    }
    template.render_to_file File.expand_path(outfile), context
`

And for the word document:
![capture](https://user-images.githubusercontent.com/1236942/44359780-3d44d580-a48f-11e8-84c6-ec79cd88a498.PNG)

This time I have a stack error:
`
NoMethodError: undefined method `next_element' for nil:NilClass
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document/blocks.rb:58:in `body'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document/blocks.rb:97:in `replace'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:128:in `evaluate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:75:in `block in manipulate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:74:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:74:in `manipulate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:61:in `process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document/blocks.rb:37:in `process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:22:in `block in evaluate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:20:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:20:in `flat_map'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:20:in `evaluate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:75:in `block in manipulate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:74:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:74:in `manipulate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:61:in `process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document/blocks.rb:37:in `process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:22:in `block in evaluate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:20:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:20:in `flat_map'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/operations.rb:20:in `evaluate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:75:in `block in manipulate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:74:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:74:in `manipulate'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/processor/document.rb:61:in `process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:75:in `block (2 levels) in process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:75:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:75:in `block in process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:72:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:72:in `process'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:61:in `render'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:49:in `render_to_string'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:43:in `block in render_to_file'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:42:in `open'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/sablon-0.3.0/lib/sablon/template.rb:42:in `render_to_file'
	from /home/ec2-user/environment/ehmanager/app/controllers/ehm/projects_controller.rb:286:in `report'
`

**Comment by stadelmanma** [comment]
Going back through old issues and I noticed this appears to be very similar to #109

**Comment by stadelmanma** [comment]
After doing some investigating I think this is due to the fact I have an each block and its contents all within a single paragraph and then those children get wrapped in a "tmp" node instead of whatever parent node type was being used before. This was discovered from a WordML insertion bug that happened when an entire conditional appeared within a single paragraph.

**Comment by stadelmanma** [comment]
Closing this as the root of the problem appears to be the same as #109.
