### ISSUE TITLE
provide else statement for conditions

### ISSUE THREAD

**Issue by deiferni** [senny/sablon#11]
I'd like to have an else statement to provide alternate content when a condition is considered falsy, e.g:

```
«foo.bar:if»
FooBar!
«foo.bar:else»
42
«foo.bar:endIf»
```

**Comment by stadelmanma** [comment]
Adding some notes for a future implementation, for myself or whoever ends up getting to it. That way I don't forget the current idea and to stir up any conversation if someone else has a different idea on how to best implement multi-block conditionals.

This would require a moderate refactor of the `Processor::Document::Block` class to allow the existence of "sub-blocks". Which in the context of a conditional statement would correspond to the content between if/elsif/else/endIf fields. Sub-blocks would implicitly end when another "sub-bock statement" was encountered or the actual end of the block itself. All statements would get recorded as control elements and be removed by `Block#remove_control_elements`

The `block` argument passed into `Sablon::Statement::Condition` would still correspond to the entire block from "if" to "endIf". However, the block instance would provide a suitable interface for the evaluation of the truthy-ness of each sub-block in order and allowing a sub-block to be retained. Removal of falsy sub-blocks and blocks that do not need to be eval'd would ideally be as simple as calling `.replace([])` on them as is currently done.
