### ISSUE TITLE
Html table default style

### ISSUE THREAD

**Issue by MO-Osama** [senny/sablon#113]
i am using Sablon.content with html table , the resulted table doesn't take the default table styling, so the header gets repeated across pages, is there's a way to set a default table style (which doesn't repeat header across pages) or create a word style dynamically and set it to the table ?

**Comment by stadelmanma** [comment]
@MO-Osama Hi glad to hear you are using Sablon! I haven't had a chance to test this yet since I'm lacking MS word currently but adding `style="tblStyle: stylename`" to the `<table>` tag will do the trick I think.

**Comment by MO-Osama** [comment]
@stadelmanma thanks for your response, that actually had the same effect of using 
Sablon.configure , the style is highlighted in MS Word, however, it's not applied, so if click on the highlighted style, it gets applied and the repeated header disappears
