### ISSUE TITLE
Search a template for a specific merge field?

### ISSUE THREAD

**Issue by cchandler81** [senny/sablon#114]
Is it possible to search a template for a specific merge field? I'd like to run unique logic if a given merge field exists on a template. For example, if the template includes a merge field for "person" and I have 2 such objects in my db, I could then generate two docs, one for each person. Hopefully that makes sense... Thanks!

**Comment by stadelmanma** [comment]
Hi @cchandler81, the MailMerge parser could probably be used on it's own, separate from a template to do what you want. Below is some roughed out (untested) code that might get you going in the right direction.

```ruby
# Load in the content however you want, the entry name you'll need to
# fetch from the zip archive is "word/document.xml"
# Some of the code in
# https://github.com/senny/sablon/blob/master/lib/sablon/document_object_model/model.rb
# might be useful in that regard
xml_node = Nokogiri::XML(content)

# returns array of SimpleField and ComplexField instances
parser = Sablon::Parser::MailMerge.new
fields = parser.parse_fields(xml_node))

# returns True if a field's expression matches "person"
one_doc_per_person = fields.any? do |fld|
  fld.expression =~ /person/
end
```

**Comment by cchandler81** [comment]
That is definitely a good starting point, much obliged.

**Comment by stadelmanma** [comment]
Glad to help, would you mind sharing a few more details on your use case?

I could see this being a useful feature for working with a "packet" of documents (read: templates) where maybe only the cover letter needs fully regenerated for each record. The rest of the files are simply cached and copied for each "person" instead of being re-parsed which is a performance intensive task for large templates.

**Comment by cchandler81** [comment]
That is essentially what I am trying to accomplish. I have "letters" that need to be generated for multiple recipients. Most of my cases are one or two pagers but I will probably have cases where only the cover page needs to be regenerated since the remaining content is the same across all recipients (e.g. a status update on work being performed the is relevant to all recipients).
