### ISSUE TITLE
Avery Labels

### ISSUE THREAD

**Issue by Svashta** [senny/sablon#116]
Hi,

I am trying to prepare one of the Avery Labels template that I would like to use with sablon and populate each label with some dynamic data. I am specifically trying to figure out how to do the loop.
Currently all the data is written out in single label instead of label by label.
Is there any way of saying NextRecord in next label or something similar?
I can't find a way to put :each and :endEach before and after the label.
Thx

**Comment by stadelmanma** [comment]
I've never tried anything like this before. A quick google to see what an Avery label template look like gives me the impression you would probably have to put the `:each` and `:endEach` after an entire row of labels. That way the row will get repeated down the page.

**Comment by stadelmanma** [comment]
No further information received, closing this for now.
