### ISSUE TITLE
Is comparing files in tests robust?

### ISSUE THREAD

**Issue by nilanjenator** [senny/sablon#128]
When comparing docx files in tests against a baseline, is there a risk that there may be minor changes in the xml node ids or sequence of xml nodes, with different versions/patches of word?

**Comment by stadelmanma** [comment]
In short yes. Microsoft Word will reindex, rename, and reorganize as it sees fit when opening and saving a document. 

However, the idea behind Sablon's doc tests against is that given a specific starting point Sablon will always modify a document in a specific way (i.e. nothing is randomly generated). To avoid undesirable changes we only ever open+save a test template when we need to make edits and we never open+save the test document fixture produced by Sablon from a template.
