### ISSUE TITLE
Change the background colour of a cell

### ISSUE THREAD

**Issue by zolotyx** [senny/sablon#129]
Hello,

Thanks for the lib, it helps a lot.

I wanted to check if it's possible to use it to change the background color of a cell in a table?

Thanks

**Comment by stadelmanma** [comment]
Hi @zolotyx it should be possible, I don't have convenient access to a windows machine to test it right now but adding the "background-color" property to the style attribute of the <td> cell in question should do the trick. That being said, I believe the colors need to be in hexadecimal (my memory fails me right now).

This fixtures below showcase the HTML processing.
https://github.com/senny/sablon/blob/master/test/fixtures/html/html_test_content.html
https://github.com/senny/sablon/blob/master/test/fixtures/html_sample.docx

**Comment by zolotyx** [comment]
Hi @stadelmanma , I did some research and didn't find a way to change the color of the cell from the inside of the cell itself.

Sure, it's possible to generate a cell with any color. but If we want to put a mailmerge template inside an existing cell, it's not possible.

Anyway, thanks for the response.
