### ISSUE TITLE
RubyZip creates a corrupted docx file on Windows

### ISSUE THREAD

**Issue by mawwerik** [senny/sablon#13]
I found this important info as the output docx file get corrupted on Windows.
https://github.com/rubyzip/rubyzip/issues/175

Would you please add "b" binary mode in render_to_file in template.rb?
File.open(output_path, 'wb') do |f|

This way it works correctly. Thank you.

**Comment by senny** [comment]
@mawwerik thanks for the heads up :yellow_heart: I added `b` to the `File.open` call.
