### ISSUE TITLE
Support for Switches

### ISSUE THREAD

**Issue by pbojinov** [senny/sablon#143]
Hi, I was wondering if Sablon supports [Switches](https://support.office.com/en-us/article/format-field-results-baa61f5a-5636-4f11-ab4f-6c36ae43508c) such as format, numeric format, or date-time format switches when using a mail merge tag?

```
{ MERGEFIELD =name \* Upper \* MERGEFORMAT } => results in PETAR

{ MERGEFIELD =created_at \@ "d-M-yy" } => results in 5-8-16
```

It comes in handy to do date formatting or in making strings lowercase/uppercase by defining this in your template and not in the exact format in your data source

Thanks!

**Comment by gumatias** [comment]
hey @pbojinov , thanks for asking. I'm also curious about it as well. This would be super handy, specially custom formatters and whatnot.

**Comment by senny** [comment]
Hi @pbojinov 

One of the design fundamentals of Sablon has always been to keep templates as lean as possible. It's much easier to write, modify and test code than templates. For this reason, formatting is something that Sablon expects you to do beforehand. This helps to keep complexity and churn in the templates low. We usually opted to go with a simple decorator that would add necessary formatting objects to the context object that's passed to Sablon.

To answer your question. I don't think this is something that we should add to Sablon.

**Comment by pbojinov** [comment]
@senny thank you for the explanation, that's totally understood to keep the library lean and have the formatting handled outside of Sablon.
