### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by cboe** [senny/sablon#15]
Hi,

I've just tried running sablon on a linux server, however, the output document is empty - on OSX it works. "Sadly", the tests seem to run without errors, except one skip:

    /usr/local/rvm/rubies/ruby-2.1.0/bin/ruby -I"lib:test" -I"/usr/local/rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib" "/usr/local/rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/content_test.rb" "test/context_test.rb" "test/executable_test.rb" "test/expression_test.rb" "test/mail_merge_parser_test.rb" "test/processor_test.rb" "test/sablon_test.rb" "test/section_properties_test.rb" 
    Run options: --seed 24583

    # Running:

    .....................................S........

    Finished in 2.269466s, 20.2691 runs/s, 24.6754 assertions/s.

    46 runs, 56 assertions, 0 failures, 0 errors, 1 skips

    You have skipped tests. Run with --verbose for details.

The verbose command doesnt seem to work, i'll try again later. I realize it's trouble to work out the problem, but do you have any pointers where to look?

ruby 2.1.0
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
nokogiri-1.6.6.2
2.1.0 :004 > Nokogiri::VersionInfo.instance.loaded_parser_version
 => "2.9.2" 
2.1.0 :005 > Nokogiri::VersionInfo.instance.compiled_parser_version
 => "2.9.2"

**Comment by senny** [comment]
@cboe I assume it has to do with your server environment. We are running sablon on CentOS servers in production and so far we had no issues.

I'm a bit confused that the tests are passing on the server, this basically means that it does not generate empty documents in all scenarios. You can try to run the [example from the executable_test.rb](https://github.com/senny/sablon/blob/master/test/executable_test.rb) on the command line and verify the output.

**Comment by cboe** [comment]
The problem was a permission issue on the server, so if anyone else gets 0 byte files, you might want to check that. Thanks!

**Comment by senny** [comment]
@cboe to help further readers would you mind to go into a little bit more detail about the issue? Where was the permission issue? On the input file? The output directory? The installed gem? The template?

**Comment by cboe** [comment]
It actually wasn't permissions, we had

    config.action_dispatch.x_sendfile_header = "X-Sendfile"

set in environments/production.rb, using nginx it should have been

    config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect'

so, totally unrelated :)

**Comment by senny** [comment]
@cboe gotcha. Thanks for the heads up.
