### ISSUE TITLE
[Question] Page breaks in docx when json is used to provide the data

### ISSUE THREAD

**Issue by suresh-jiffler** [senny/sablon#151]
I provide an option to the user if he wants the output docx to have either single or multiple data/record per page. If the user selects single data/record per page, the output docx will have pages(using loops) in which each page has only one data/record. 

Is it possible to achieve this using sablon? Sorry, I couldn't find anything about page breaks in the `README.md` although this might seem trivial

**Comment by senny** [comment]
Hi @suresh-jiffler 

You can make two templates, one with a "single record per page" and one with "many records per page". Then simply render the corresponding template based on the user selection.

Alternatively, you could experiment with wrapping a page-break with an IF conditional but I haven't tried if that will work out.
