### ISSUE TITLE
Adding table to html creates corrupted file

### ISSUE THREAD

**Issue by amaks** [senny/sablon#159]
When I am adding table tag to the html and create output file, I can not open it due to the error "Work experienced an error trying to open the file". Without table html is fine.  I have used Readme example for HTML

**Comment by senny** [comment]
Hi @amaks, could you provide the sample HTML fragment that corrupts the document? Ieally a reduced example that highlights the issue.

**Comment by amaks** [comment]
This is example which I have used
html_body =  <<-HTML.strip
<div>
    This text can contain <em>additional formatting</em> according to the
    <strong>HTML</strong> specification. As well as links to external
    <a href="https://github.com/senny/sablon">websites</a>, don't forget
    the "http/https" bit.
</div>

<p style="text-align: right; background-color: #FFFF00">
    Right aligned content with a yellow background color.
</p>

<div>
    <span style="color: #123456">Inline styles</span> are possible as well
</div>

<table style="border: 1px solid #0000FF;">
    <caption>Table's can also be created via HTML</caption>
    <tr>
        <td>Cell 1 only text</td>
        <td>
            <ul>
                <li>List in Table - 1</li>
                <li>List in Table - 2</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <table style="border: 1px solid #FF0000;">
                <tr><th>A</th><th>B</th></tr>
                <tr><td>C</td><td>D</td></tr>
            </table>
        </td>
    </tr>
</table>
HTML
context = {
  article: Sablon.content(:html, html_body) },
  # Or use html: prefix to make sablon parse the value as HTML.
  # Does the same as above.
  'html:article' => html_body
}
template.render_to_file File.expand_path("~/Desktop/output.docx"), context

**Comment by amaks** [comment]
It seems like jruby is causing a problem with creation.

**Comment by stadelmanma** [comment]
@amaks Unfortunately  sablon doesn't support jruby, we get odd errors and failures due to what I believe is some implementation differences in the Java version of the nokogiri gem. 

https://github.com/senny/sablon/issues/141#issuecomment-550096543
