### ISSUE TITLE
Is it possible to get a list of available placeholders in the document?

### ISSUE THREAD

**Issue by Xorg1984** [senny/sablon#16]
ex:
template = Sablon.template(File.expand_path("~/Desktop/template.docx"))
template.get_placeholders # ['title','author', ...]

**Comment by senny** [comment]
@Xorg1984 currently there is no public API to access the fields. Also I'm not sure how easily such a function can be generalized. The fields can be nested within loops and conditionals, they can also use local variables. This makes the expression not very useful outside of it's context.

What are you trying to achieve?

**Comment by Xorg1984** [comment]
my task - get all document placeholders (this will be a simple strings), show interface to set values to placeholders and then generate a new document with values
maybe parse document independently?  what way you recommend?

**Comment by senny** [comment]
Sablon was not built with that use-case in mind. Therefore I won't introduce public API to get the output you'd like. The behavior would be too brittle and not clear when loops and conditions are in play.

Having said that, you can use the internal building blocks of Sablon to extract the data you need. Following is a simple script executed against a fixture template:

```ruby
path = "/Users/senny/Projects/sablon/test/fixtures/recipe_template.docx"

parser = Sablon::Parser::MailMerge.new
fields = []

Zip::File.open(path).each do |entry|
  entry_name = entry.name
  content = entry.get_input_stream.read
  if entry_name == 'word/document.xml' || entry_name =~ /word\/header\d*\.xml/ || entry_name =~ /word\/footer\d*\.xml/
    document = Nokogiri::XML(content)
    fields += parser.parse_fields(document)
  end
end

fields.map(&:expression)
# => ["=title", "=intro", "ingredients:each(ingredient)", "=ingredient.amount", "=ingredient.name", "ingredients:endEach", "=preparation", "=metadata.generator", "=details.author.name"]
```

Depending on your templates you might just need to parse `word/document.xml`.

**Comment by Xorg1984** [comment]
Thanks!

**Comment by hahmed** [comment]
@avdovin how did you get on this, did you manage to get what you want working?

I am also looking to read all merge_fields from the document so the user can fill out the fields in the interface.

Was the code in the comment sufficient? https://github.com/senny/sablon/issues/16#issuecomment-103446793 

Thanks
