### ISSUE TITLE
Remove empty pages on the generated docx

### ISSUE THREAD

**Issue by WWGate** [senny/sablon#166]
Hello Guys,

I'm generating Docx files using this gem, which is great.
the only issue I'm facing that there are empty pages on some cases.

Is there any way to know if the generated document has an empty page and remove it?

Appreciate all the help I can get

**Comment by senny** [comment]
Hi @WWGate

I don't think we have anything in Sablon to help that case. Do you know the reason why you end up with empty pages sometimes? Is it because you are using conditionals that with certain context will not render any data on a given page or are you seen something that is not reproducible?

**Comment by WWGate** [comment]
Hello @senny,

Yes I'm using conditions to display some text and populate user answers inside the docx file, I display user answers and append some sentences to it, so if the populated text comes at the end of the page and the populated text has '\n\n' at the end of it and the next page has a page break, the final docx will have an empty page as it contains the '\n\n'.

If I remove '\n\n' from the text then I'll break the alignment between paragraphs.
Do you have any idea to fix it?

**Comment by WWGate** [comment]
thank you @senny, I'll try to achieve the same
