### ISSUE TITLE
style application

### ISSUE THREAD

**Issue by alepore** [senny/sablon#17]
Apologies in advance if this is not pertinent to the gem: i'm not sure if it's some bug or i'm bad at Office 2011.

I'm trying to apply some list styles from markup data.
I've added the `ListBullet` style to the template, styles.xml source:
```xml
<w:style w:type="numbering" w:customStyle="1" w:styleId="ListBullet">
  <w:name w:val="ListBullet"/>
  <w:basedOn w:val="Nessunelenco"/>
  <w:uiPriority w:val="99"/>
  <w:rsid w:val="005547DB"/>
  <w:pPr>
    <w:numPr>
      <w:numId w:val="25"/>
    </w:numPr>
  </w:pPr>
</w:style>
```

and i see it on the generated document source:
```xml
<w:p>
  <w:pPr>
    <w:pStyle w:val="ListBullet"/>
  </w:pPr>
  <w:r>
    <w:t xml:space="preserve">my content</w:t>
  </w:r>
</w:p>
```

But i don't see any list style on the document, it's just normal text.
Any thoughts?

**Comment by senny** [comment]
@alepore Can you upload a ruby script and a sablon template that reproduces the error? This would go a long way to help me debug the issue.

**Comment by alepore** [comment]
@senny thanks, simple reproduction script: http://s000.tinyupload.com/index.php?file_id=38574526047958687033

**Comment by senny** [comment]
@alepore thanks for the reproduction. There was an issue with your template and with some minor modifications I was able to get the desired output:

![screen shot 2015-06-23 at 09 22 56](https://cloud.githubusercontent.com/assets/5402/8300914/189b1412-198a-11e5-9209-8d5bb83023e2.png)

While you did see the style "ListBullet" when authoring the `template.docx` it was not actually part of the template. Word has a root template called `Normal.dot`. That's where common styles are saved. While visible in Word, the styles of `Normal.dot` are not part of your template by default.

The following steps allow you to manage the styles that are part of your template:
![screen_shot_2015-06-23_at_09_30_24](https://cloud.githubusercontent.com/assets/5402/8300992/be94d8e4-198a-11e5-9399-bb6478a8a692.png)
![screen_shot_2015-06-23_at_09_30_38](https://cloud.githubusercontent.com/assets/5402/8300998/c44d3024-198a-11e5-85a0-637aed86b723.png)
![screen_shot_2015-06-23_at_09_30_48](https://cloud.githubusercontent.com/assets/5402/8301001/c7aed2e0-198a-11e5-8cf4-48d0d71acc8c.png)

Once you copied the styles over from `Normal.dot` and save your template the example should work as expected. As Sablon matures I'll add more template validation and introspection. It's a common pitfall and I'd like to make it more explicit.

Thanks for reporting. I'm going to close the issue but please report back if you get it working or still have questions related to your example.

**Comment by alepore** [comment]
Thanks for reply!
The gem is really easy to use, the hard part is definitely the word template :)

Something is wrong here because i see `ListBullet` on both template.docx, output.docx and Normal.dot 
but i still don't see the style on the output (but i can manually apply it)

![screen shot 2015-06-23 at 10 10 44](https://cloud.githubusercontent.com/assets/557414/8301758/4f0159c4-1991-11e5-951b-4afa0de650dd.png)

![screen shot 2015-06-23 at 10 11 17](https://cloud.githubusercontent.com/assets/557414/8301757/4e5b9e8a-1991-11e5-8289-3c6f3a27a521.png)

![screen shot 2015-06-23 at 10 20 44](https://cloud.githubusercontent.com/assets/557414/8301798/8ebb47be-1991-11e5-8da8-647497a76d37.png)

**Comment by senny** [comment]
@alepore did you try copying over the `ListBullet` style from `Normal.dotm` and overwrite the one in `template.docx`. It might very well be that one is only a reference to the other. Copying over the style did the trick for me...

**Comment by alepore** [comment]
mhh i think i tried any way to add/copy the style.
the problem is with the list itself, because if a create another formatting style (like red color) and name it `ListBullet` it works.
Maybe is something with my list style...

**Comment by senny** [comment]
@alepore that sounds very much like the issue I described... You can't change the styles of `Normal.dotm` so when you modify a given style it's saved in the template itself. To use the default "ListBullet" style you should:
1. Open your template
2. Go to the organizer as described above
3. Copy over "ListBullet" from "Normal.dotm" into your template
4. Save & run Sablon

Those were the exact steps I used with your example.

**Comment by alepore** [comment]
@senny if i start with a clean setup and i open my template i *don't* have `ListBullet ` on `Normal.dotm` but only on the template.
i can recreate the style, there's a optional checkbox to add it to `Normal.dotm`, then i can follow your steps but i still don't see the list ;(

**Comment by senny** [comment]
@alepore that sure is strange. If I open a blank word document in my case, the `Normal.dotm` has all the predefined styles. Maybe you somehow managed to change your `Normal.dotm`... Anyway, if using the style in the template document works, it must be defined somewhere. It's basically a matter of copying the right definition into the template to get it working. Modifying the style slightly usually gets the job done.

**Comment by alepore** [comment]
Just FYI:
I used Office 2016 for mac and now it works.
There was definitely something wrong with Office 20111 for Mac.

Thanks again for support!
