### ISSUE TITLE
Use mail merge fields in LibreOffice Writer

### ISSUE THREAD

**Issue by Yegorov** [senny/sablon#171]
It possible add variable in LibreOffice Writer?
![LibreOffice](https://user-images.githubusercontent.com/2566462/120291968-8840d800-c2cc-11eb-965f-ba190b369dbd.png)

**Comment by senny** [comment]
Hi @Yegorov 

The gem was authored against Microsoft Word. It's possible that you could add support for LibreOffice but it's unlikely that support will be added by gem maintainers. If you are looking to add support, have a look at `Sablon::Parser::MailMerge` to get started.

Best,
Yves
