### ISSUE TITLE
Nested lists support

### ISSUE THREAD

**Issue by alepore** [senny/sablon#20]
I would like to try adding support for nested lists if it's not impossibile... any help on how to start? :)

Thanks

**Comment by senny** [comment]
What support do you have in mind? Markdown support for nested lists? Template support for nested lists? Other?

**Comment by alepore** [comment]
I have some markdown with two-levels lists and would like to support them:
```
- item
 - item
 - item
- item
```

**Comment by senny** [comment]
ok got it! Awesome :yellow_heart:.

So basically what you'll have to do is figure out how Word represents nested lists in it's document.xml. Simply create a blank document with some nested bullet and numbered lists and inspect the document (it's just a zip file).

From there you can try to change the [WordML renderer](https://github.com/senny/sablon/blob/master/lib/sablon/redcarpet/render/word_ml.rb) to make the right transformations from your Markdown to the required wordml.

You can also peek ad [Pandoc](http://pandoc.org/). It's written in Haskell and most likely has support for markdown to docx transformations with nested lists.

Hope that helps.

**Comment by alepore** [comment]
Thanks, it definitely helps.

I've taken a look, a  problem seems that redcarpet puts nested list items under the same "container" of the root item, which is ok in HTML (`<ul>`) but not in wordml (`<w:p>`).
Each item must be in a different, separate paragraph https://msdn.microsoft.com/en-us/library/office/ee922775(v=office.14).aspx#odc_Office14_ta_WorkingWithNumbering_MarkupMultiLevel

Will do some more tests :)

**Comment by alepore** [comment]
FYI i succesfully tweaked the renderer for my needs (nested lists) but the code is pretty hack to workaround some weird redcarpet behaviours which i frankly don't fully understand.
 
code here https://gist.github.com/alepore/b0b28846c46da681dd6e

**Comment by senny** [comment]
@alepore hey! Things have changed quite a bit since I started working on markdown insertion. If you are still using sablon you may want to check some new features out.

First, I noticed that my approach using a redcarpet formatter was very limited and had serious flaws when generating documents. It was quite easy to create documents that could not be opened by word. I've decided to [deprecate and later remove markdown insertion](https://github.com/senny/sablon/commit/1eb97077f08d0c0bf0cd4dce097c2a53551e64e1) completely. As a replacement, I started working on HTML insertion. Currently the focus was on getting the output from the [Trix editor](https://github.com/basecamp/trix) working. The new HTML insertion turned out to work quite well with limited markup. With a few additions I was able to achieve the same and better results for Markdown insertion by converting it to html first.

If you are still using Sablon I would be glad to hear your thoughts. Cheers, Yves.

**Comment by alepore** [comment]
Hey!
Yes i'm using it but i think i will never touch again that code ;)

Anyway, i moved all my app data from HTML to markdown to have some sort of "standard" format.
Users was creating HTML with ckeditor and copy/paste and the result was  a very big messy HTML..

**Comment by senny** [comment]
@alepore even if you are using Markdown as an input format. Converting it to html before running sablon should give you much better results now. Nested lists are working, numbering across multiple lists has been resolved and it should be way harder to get invalid documents. Anyway, let me know if you hit any issues down the road.

**Comment by alepore** [comment]
HTML insertion work well!
Thanks, i switched from markdown.

Not i must understand why i always get numbered lists on word for `<ul>`, but that's probably a problem of my template.

**Comment by alepore** [comment]
@senny are you sure you can use `<w:pStyle w:val="ListBullet"/>` on lists? :)
reading some stuff here... http://www.lenzconsulting.com/wordml/#officexml-CHP-2-SECT-5.4.4

**Comment by senny** [comment]
@alepore did you look at the examples in the repository? I'm pretty certain we have bulleted lists in our application.

**Comment by alepore** [comment]
@senny no i didn't find the `ListBullet` style on the repo templates...

**Comment by senny** [comment]
Weird. It should be in there somewhere. The thing is that it's not a normal ListStyle. It's only used as reference style on the MultiLevelList style. That's only necessary to make sablon recognize that multi level list style. There's probably a better way to flag the style but I haven't found one yet.

I don't have word on the computer I'm using right now, so I can't post any screenshots or check if the templates actually miss the style. I'll try to follow up on this later on.

**Comment by alepore** [comment]
quick follow up:
i didn't find a way to change nested lists bullets on my template, but it works using the https://github.com/valgusk/sablon/ (i think this is the relevant commit https://github.com/valgusk/sablon/commit/b03bcd80f28f3d9d018aa5c361afa76f242178f7)

**Comment by senny** [comment]
@valgusk are you up for submitting your patch as a PR to this project? Would require some tests around the changes and maybe some reasoning what was causing issues.

**Comment by valgusk** [comment]
@senny, I will tend to extraction of this feature from my code this week. My fork is purely for making things work for my usage of your project though, so I bet there would be more elegant ways to do this.
