### ISSUE TITLE
can't dup NilClass when render template

### ISSUE THREAD

**Issue by Xorg1984** [senny/sablon#22]
Hey,
When i try to render template i get an error - can't dup NilClass
The error occurs in the file *lib/sablon/content.rb line 59*

This code in file *lib/sablon/parser/mail_merge.rb*  fixes problem for me 

```ruby
def replace_field_display(node, content)
  paragraph = node.ancestors(".//w:p").first
  display_node = node.search(".//w:t").first
  unless display_node.nil?
    content.append_to(paragraph, display_node)
    display_node.remove
  end
end
```

**Comment by senny** [comment]
@Xorg1984 can you please attach your template or a template that reproduces the problem along with the sablon script you are using to render it?

**Comment by Xorg1984** [comment]
the error occurs with [this template](https://dl.dropboxusercontent.com/u/545979/KVADREX-36.docx)

**Comment by senny** [comment]
@Xorg1984 can you attach a script that renders the template as well?

**Comment by Xorg1984** [comment]
To reproduce issue try run this test script

```ruby
#!/usr/bin/env ruby
require "sablon"

template = Sablon.template('KVADREX-36.docx')
context =
{
  client: {
    "id"=>53, "ct_cd"=>0, "fname"=>"Петров", "lname"=>"Тестов",
    "mname"=>"Васильевич", "short_name"=>"Тестов К. А.", "email"=>"test@test.com", "interest_id"=>5,
    "status_id"=>1, "source_id"=>1, "cooparation_stage_id"=>nil,
  },
}
template.render_to_string(context)
```

if context is empty hash i get another error:
lib/sablon/parser/mail_merge.rb:20:in `replace_field_display': undefined method `remove' for nil:NilClass

**Comment by senny** [comment]
@bensie your word document contained traces of invalid merge fields (with the expression `=client.lname`). While I'd recommend to clean up those broken references, theres no reason for `sablon` to crash like this. I pushed a fix and will release `0.0.17` shortly.

**Comment by senny** [comment]
[`0.0.17`](https://rubygems.org/gems/sablon/versions/0.0.17) is out.

@Xorg1984 thank you for reporting.

**Comment by Xorg1984** [comment]
@senny thanks you for the quick reply and fixing crash! looks good :)
