### ISSUE TITLE
Support For Empty Fields

### ISSUE THREAD

**Issue by veered** [senny/sablon#24]
It takes me a while to add a new mailmerge field and as far as I can tell there is no keyboard shortcut. However, there is a shortcut for adding a new empty field with `Cmd+Fn+F9` on OSX or `Ctl+F9` on Windows. If this type of field was supported it could significantly speed up the templating process.

**Comment by senny** [comment]
Thank you @veered for your suggestion.

The code is written in such a way that you could theoretically replace the [MailMerge parser](https://github.com/senny/sablon/blob/master/lib/sablon/parser/mail_merge.rb) with another implementation.

For us Mail Merge fields are working quite well but please do investigate wether support for Empty Fields is easily addable. If you have any questions, feel free to reach out.

**Comment by veered** [comment]
Is there a keyboard shortcut for adding Mail Merge Fields?

**Comment by senny** [comment]
I usually just copy and paste them.

**Comment by veered** [comment]
At least for me copying and pasting them does not work Here is a Word macro that makes inserting Mail Merge Fields easier:

```VB
Sub InsertMailMergeField3()
'' create an MailMerge field from the selection; or create one from a dialog box

Dim selection_empty As Boolean, selection_text As String
selection_empty = Selection.Type = wdSelectionIP
selection_text = Selection.Text

If selection_empty Then
    Dim xPrompt As String, xTitle As String, xDefault As String
    xPrompt = "Insert Tag Name"
    xTitle = "< QUALIA TAGGER >"
    selection_text = InputBox(xPrompt, xTitle, xDefault)
End If
  
Selection.Fields.Add Range:=Selection.Range, Type:=wdFieldEmpty, Text:="MERGEFIELD =" & selection_text, PreserveFormatting:=True

End Sub
```

**Comment by senny** [comment]
@veered awesome! thanks for the follow up. :yellow_heart:
