### ISSUE TITLE
Compatibility with Mac / Pages 'Export As .docx'

### ISSUE THREAD

**Issue by fatuhoku** [senny/sablon#29]
The output is identical to the input. I don't have Word for Mac installed. Is this required?

**Comment by senny** [comment]
Most likely means that something is not good with the merge fields you put in place. If you upload the template and the script to execute on GitHub I'll have a look.

**Comment by senny** [comment]
Closing this for now. Please report back if you have additional information to help me investigate the issue further.

The gem was designed for Word and Word for Mac. It relies on some Word-ML structures that are generated when using merge-fields. I doubt that the pages export generates these structures the same way.
