### ISSUE TITLE
Is this gem working?

### ISSUE THREAD

**Issue by nav0285** [senny/sablon#30]
I tried using this gem but it looks like gem is not working. i tried a sample template docx file ( Dear «=title» ) and tried to pass the context = { title: 'sablon' }. 

    src = Rails.root.join('public','sample.docx')
    template = Sablon.template(File.expand_path(src))
    context = {title: "Fabulous Document"}
    dst = Rails.root.join('public', 'report.docx')
    template.render_to_file(File.expand_path(dst), context)
    File.open(dst, 'r') do |f|
       send_data f.read.force_encoding('BINARY'), :filename => 'report.docx', :type => "application/docx"
    end

**Comment by senny** [comment]
@nav0285 it is working and running in production. Did you insert `«=title»` as raw text or using the "Merge Field" functionality? If you did use a merge field, you can upload the document somewhere and I'll check.

**Comment by nav0285** [comment]
[sample.docx](https://github.com/senny/sablon/files/366282/sample.docx)

The above one is the sample docx file.

**Comment by nav0285** [comment]
@senny i tried your template and its working good. I used merge field functionality and i'm getting «title» in this way... I googled but still could not find how to get «=title» .

**Comment by nav0285** [comment]
@senny sorry. I made a mistake when I was inserting mail merge fields. Thanks... This gem is working awesome.
