### ISSUE TITLE
Merged field text not being replaced

### ISSUE THREAD

**Issue by mammothcow** [senny/sablon#32]
Run across an issue and not sure what is wrong. I have a merged field in a title that is putting the string I want in but does not remove the entire merged field text.

The code for this is below and the two files referenced in the code 
[template.docx](https://github.com/senny/sablon/files/437175/template.docx)
[output.docx](https://github.com/senny/sablon/files/437176/output.docx)

are attached.

emplate = Sablon.template("template.docx")

context = {
    system_name: "Jeff's Wonderful System"
}

template.render_to_file "output.docx", context

**Comment by senny** [comment]
mmm just had a quick look at this. Somehow the merge field has a slightly different structure than what sablon expects. Could be something because of style changes (font etc.) later on.

I'll see if we can get sablon to support this structure as well.

**Comment by senny** [comment]
I just released version `0.0.20`. It should contain a fix to solve this issue. Thank you for reporting 💛
