### ISSUE TITLE
Example using nested loops

### ISSUE THREAD

**Issue by mammothcow** [senny/sablon#33]
I have been trying to understand how nested loops work. Not sure what sablon is looking for in the nested loop, i.e. the part of the "each" statement is not in the context passed in. 

See below what I mean:

1  \<\<widgets:each(anItem\)>\>
2     \<\<anItem.details(foo)\>\>
3         \<\<=foo.description\>\>
4     \<\<anItem.details:endEach\>\>
5 \<\<foo:endEach\>\>

What I am seeing is that the inner loop is executing correctly but nothing shows up in the output document for what is expressed on line 3 above.

I am not sure if the syntax I am using is correct or what else I am doing incorrectly.

**Comment by senny** [comment]
@mammothcow could you upload a minimal sample template and the necessary sablon script to run it? This goes a long way to debug the issue.

**Comment by mammothcow** [comment]
I've got the nested loops working. This was not a bug, a little more documentation around how to access things in the nested loops would be very helpful. 

Other than that this works like a champ.

BTW... the way I thought it would work was correct.
