### ISSUE TITLE
can use ruby function in docx template

### ISSUE THREAD

**Issue by ariawanzero** [senny/sablon#38]
Hi I want to ask i have date like '2015-01-01' can i use ruby function in docx like this '2015-01-01'.strftime('%b %Y') so it result "January 01"

**Comment by senny** [comment]
You can do this by wrapping your data with an object. This allows you to define a formatter method that you can then call from your template. This will look something like this:

```ruby
require "sablon"
template = Sablon.template(File.expand_path("~/Desktop/template.docx"))

DateStruct = Struct.new(:date) do
  def day_and_month
    date.strftime('%b %Y')
  end
end

context = {
  obj: DateStruct.new(Date.parse(2015-01-01)),
}
template.render_to_file File.expand_path("~/Desktop/output.docx"), context
```

And then in your template you can call it using:

```
«=obj.day_and_month»
```

The naming in my example is a bit arbitrary but you should get the general idea. I'm sure you can find better suited names for the objects in your domain.
