### ISSUE TITLE
Question/Idea: Implications of Numbering being a singleton in multi-user rails app

### ISSUE THREAD

**Issue by stadelmanma** [senny/sablon#43]
Could there be any issues with the above class being a singleton if say two users generated a docx file at the same time? It seems like the definitions being registers would get fouled up since if I am thinking correctly the rails app would only ever have one instance of Numbering available to work with.

```ruby
    def reset!
      @numid = 1000
      @definitions = []
    end

    def register(style)
      @numid += 1
      definition = Definition.new(@numid, style)
      @definitions << definition
      definition
    end
```

Could it potentially be more robust to register a numbering instance on the Context object being passed around and use that instead? You should be able to maintain the same expected behavior if Context.trasnform is moved out of Document.process and into the template.rb file (likely in the render method).

- [x] Convert Context from module into class
- [ ] Register a local Processor.Numbering instance to the Context instance

**Comment by senny** [comment]
@stadelmanma you are totally right. It always bugged me (and still does) that this is a singleton. This was a quick-hack to get things out the door. I have since moved away from the work that relied on sablon. I don't have a lot of resources to work on the gem and these things just stayed the way they were.

I'd be amazing if you had time to work on a refactor. I can give guidance if some questions pop up in the process.

**Comment by stadelmanma** [comment]
Can do, I need to make an actual Context class to properly resolve the path to my partial directory so I'll add the Numbering class reference to that as well.

**Comment by senny** [comment]
@stadelmanma if you plan on doing a deeper refactoring, it would be nice if we can merge it piecewise. With my current resources it is harder to review a giant diff. Let me know if you have any questions and thanks a lot for your work 💛

**Comment by stadelmanma** [comment]
I'll submit the changes to context.rb separately from the Numbering class changes, although they will be built on top of the context.rb changes.

**Comment by stadelmanma** [comment]
The first PR is up which forms the base for the Numbering fix. However, as I started testing my fixes to Numbering I noticed that we will run into an issue with some of the current API documented in the README. In order to track the numbering at the instance level, it requires the Context class instance to be passed through the wrap method in content.rb.

```ruby
      def wrap(value, context)
        case value
        when Sablon::Content
          value
        else
          if type = type_wrapping(value)
            type.new(value, context)
          else
            raise ArgumentError, "Could not find Sablon content type to wrap #{value.inspect}"
          end
        end
      end
```

Which means, this block won't be possible anymore but it seems like you already have logic to handle by specifying the type with the hash key.

```ruby
  def self.content(type, *args)
    Content.make(type, *args)
  end
```
