### ISSUE TITLE
Expanding the HTML parsing

### ISSUE THREAD

**Issue by stadelmanma** [senny/sablon#47]
I am going to expand the HTML parsing capabilities of sablon in my fork and can merge the changes back into your repo if desired. Expanding the HTML capability allows me to leverage the power of the native ERB templating engine instead of trying to reinvent the wheel and port those same features into sablon directly.

Relevant Issue on in my repo: https://github.com/stadelmanma/sablon/issues/9

Checklist added on 07/25/17

- [x] Implement support for the `<span>` tag
- [x] Implement support for a limited set of attributes specified by the `style=` attribute
    * Do this in a flexible way so it can be relatively easy to add additional styles in the future
    * Allow it to function on both the run and paragraph levels
- [x] Implement support for the `<sup>` and `<sub>` tags
    * Relevant branch on my fork: [support-sup-and-sub-tags](https://github.com/stadelmanma/sablon/tree/support-sup-and-sub-tags)
- [x] Implement support for Hyperlinks via `<a>` tags 
    * I think this will first require a refactor of how we handle a document template. Currently template files are read and written sequentially, instead we would really need more a "live DOM" where all aspects of a word doc are available since hyperlinks are stored in the `document.xml.rels` file. A "live DOM" approach would also benefit our existing logic in the numbering process and significantly simplify the logic required to support images (see #54).
    * See #83 for an implementation without the refactor mentioned below
- [x] Implement support for parsing of HTML `<table>` tags
    * I ran into some issues with this one my fork where it seemed like not all content was being properly generated inside a table. Lists are the only one that comes to mind initially but I didn't test images/figures.
    * I implemented the `<caption>` tag differently on my fork but perhaps I should do it according to the HTML5 spec here using similar logic, although implementing support for `caption-side` might be hard and I don't know if I can/want to add a table reference like in my fork. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption), [W3 Schools](https://www.w3schools.com/tags/tag_caption.asp)
    * Relevant branches on my fork: [support-table-tag](https://github.com/stadelmanma/sablon/tree/support-table-tag), [add-th-element](https://github.com/stadelmanma/sablon/tree/add-th-element)
- [ ] Allow inline HTML insertion that only replaces the merge field itself, not the entire run
    * This would only be allowed if the HTML content only contained inline tags (i.e. `w:r`, `w:hyperlink`, etc.),
    * I'm not sure how to best assert that only inline tags were used probably a whitelist based on the allowed childnodes of a `w:p` tag as defined in the OOXML spec.

**Comment by senny** [comment]
Patches that expand HTML insertion for general purpose use are definitely welcome. Things that tend to be more use-case / project specific are better done in a fork. If we can tweak the HTML converter to allow custom extensions that would be even better. Then the extensions could live in app code or gems without a necessary fork. Do you think your changes are general purpose or more on the specific side of things?

**Comment by stadelmanma** [comment]
In my mind the changes are general purpose. The first round will involve adding support for the `<span>` tag to create individual runs within a paragraph. Building upon that I want to add more styling options, text color, alignment, alternative methods to make bold and italics typeface, etc.  

i.e. in the final product you could do something like:
``` html
<p style="text-align: center; color: #DDDDDD">
Paragraph text content, centered and gray
  ...
  <span style="font-weight: bold">Some bold Text</span>
  ...
  <span style="background-color: yellow">Some highlighted text</span>
  ...
</p>
```
Obviously all CSS styles wouldn't be, nor could be supported but a basic set to cover the common cases in MS Word.  


After thinking about #48 and hyperlink injection it would be great if "inline" elements i.e. `<span>`, `<a>`, etc. didn't have to replace the entire paragraph but that might be beyond the scope of my needs.

**Comment by stadelmanma** [comment]
@senny after thinking about #48 what are your thoughts of allowing HTML substitution that doesn't replace the entire paragraph **if** the HTML elements being adding are considered "inline" i.e. `<a>`, `<b>`, `<i>`, `<span>`. 

I think there would be a clear enough break in the logic to justify full paragraph replacement if you use block level elements `<div>`, `<p>`, `<ul>`, etc. that it shouldn't confuse users. Currently the supported inline tags can't exist outside of a block level tag so a change like this wouldn't break existing backwards compatibility.

**Comment by senny** [comment]
@stadelmanma I'm 👍  if we can find a solution that works for both paragraph and inline replacements. We could even use it to provide better content abstractions. Something like:

```ruby
Sablon.content(:hyperlink, "Click Me", "https://google.com")
```

I think it should be fine if we CASE the behavior on the fact that the provided HTML contains at least 1 paragraph element.

**Comment by stadelmanma** [comment]
@senny as I work through supporting the style tag (I'm almost ready for a PR that will build off of #51) I am finding myself setting up blocks like the following:

```ruby
      # converts CSS => OpenXML
      attr_map = {
        'background-color' => ->(v) { return 'highlight', v },
        'font-weight' => ->(v) { return 'b', nil if v =~ /bold/ },
        'font-style' => lambda { |v|
          return 'b', nil if v =~ /bold/
          return 'i', nil if v =~ /italic/
        },
        'text-align' => ->(v) { return 'jc', v }
      }

...
     # maps HTML block element => MS Word Paragraph style
      styles = { 'div' => 'Normal', 'p' => 'Paragraph', 'h' => 'Heading',
                 'ul' => 'ListBullet', 'ol' => 'ListNumber' }

...
     # maps element style tags => OpennXML styles
      styles = {
        'span' => {}, 'strong' => { 'b' => '' },
        'b' => { 'b' => '' }, 'em' => { 'i' => '' },
        'i' => { 'i' => '' }, 'u' => { 'u' => 'single' }
      }
```

In my mind these are great candidates to define in a configuration module. The config could be altered by the user allowing them to support more styles, HTML tags, etc. to suit their needs when our defaults aren't sufficient. This fits right in with your proposal to make HTML conversion more extensible by the end user. I just couldn't think of *how* to make it extendable when you first brought up the idea. 

What is your opinion on implementing a `Sablon.config` module to store all of these defaults?

**Comment by stadelmanma** [comment]
@senny I have implemented support for the `<s>`, `<sup>` and `<sup>` HTML tags in my branch [support-sup-and-sub-tags](https://github.com/stadelmanma/sablon/tree/support-sup-and-sub-tags). Initial support for parsing of HTML tables is in branch [support-table-tag](https://github.com/stadelmanma/sablon/tree/support-table-tag). Both of these future PRs rely on the refactors added by #55. 

I'll make PRs for those once we get the details of #55 worked out.

**Comment by stadelmanma** [comment]
I also have support for parsing HTML tables into WordML tables with proper styling implemented on a branch in my fork. Its not perfect, because you can't nest additional block level tags (i.e. `<div>`, `<p>`, `<ul>` and `<ol>`, `<table>` inside a `<td>` element.

It appears that it would take a pretty major refactor of the AST generation to handle those tags inside a table cell. MS Word has no notion of paragraphs inside paragraphs (block level inside block level) and the current AST builder is rooted in that logic. Table cells can hold anything so they end up being an exception to the rule.

**Comment by amrfaisal** [comment]
Just to give you an idea about capabilities could be handled by having HTML insertion: https://docxtemplater.com/demo/#html
