### ISSUE TITLE
about comment tag

### ISSUE THREAD

**Issue by gamesover** [senny/sablon#56]
in `document.rb` line 174, `when /comment/` makes it starts comment the document as long as there is a key contains `comment`. In my opinion, it shall be improved with an unique key to trigger comment. Since the current any key contain `comment` is too general. To be frank, in my project, one of my key is the exact as `comment`. Originally, I rename it to `a_comment`. But it still trigger the comment

**Comment by senny** [comment]
Hi @gamesover,

This sounds like a bug for sure. Would you be open to work on a patch>
