### ISSUE TITLE
Don't work with rubyzip < 1.1.2

### ISSUE THREAD

**Issue by jairud-garcia** [senny/sablon#57]
OutputStream#write_buffer don't receive parameter in version under 1.1.2 generating a ArgumentError: wrong number of arguments (given 1, expected 0)
 in: 
rubyzip-1.0.0/lib/zip/output_stream.rb:55
sablon-0.0.1/lib/sablon/template.rb:21

Please upgrade the gemspec

**Comment by stadelmanma** [comment]
@jairud-garcia version 1.1.1 is the first version to have the argument. I have updated the gemspec to require `'rubyzip', ">= 1.1.1"` instead of 'rubyzip', ">= 1.1" thanks!
