### ISSUE TITLE
Create a configuration object

### ISSUE THREAD

**Issue by stadelmanma** [senny/sablon#62]
There are several areas in sablon that would lend themselves well to a general configuration object that could replace current blocks of conditional code. Most notably the style attributes added in #55. This opens the door to easily allow the end user to add/change functionality without needing to change the code itself, especially in cases where it is not practical i.e. a Rails app.

Other possible candidates could be regexp's used in OperationConstruction#consume and Template#render.

**Comment by stadelmanma** [comment]
I think one good way to build a strong API around this for adding support for new tags via a config module would be a 'Tag' class or struct along with an accompanying `register_tag` and a `remove_tag` method. Those methods would act as getters and setters for the supported tags hash allowing me to limit direct access (or at least not advertise it i.e. use at your own risk). One caveat with this is that I want the end user to be able to add their own AST classes if needed as well so the `tag` struct would need to include an AST class reference that likely defaults to either Paragraph or Run.

Something similar could be implemented for supporting additional style attributes as well.

**Comment by senny** [comment]
@stadelmanma I'm not totally convinced yet that this configuration is something that would be used by the majority of sablon users. I can see use in being able to specify the style class mapping. However, I doubt that adding AST nodes is something that needs to have a prominent API. Somebody who is going down that route will need to be familiar with Sablon internals. At that point we could have a low level entry point and don't need a abstracted "configuration" for it.

**Comment by stadelmanma** [comment]
@senny I agree that the vast majority of users wouldn't need to use a configuration object at all because they only need the basic functionality. I think that means you've successfully built the gem so nearly everyone can use it right out of the box. This is about the smaller pool of users that need to customize functionality to varying degrees.

Essentially adding a new AST node wouldn't be part of the main API it would get shuffled over into the options hash, for that exact reason. Since in most cases a person is only going to add new inline tags for some miscellaneous style.  

The benefit of storing AST node information on the `tag` class is that it allows us to refactor and streamline all of the code in the html converter itself. The only reason it would be an available option is that there shouldn't be any additional overhead in providing the end user that added degree of flexibility to extend the gem if they really want to dig into things.
