### ISSUE TITLE
ArgumentError: Don't know how to handle node: #<Nokogiri::XML::Element:0x3fc5e96cf3d8 name="i" children=[#<Nokogiri::XML::Text:0x3fc5e96ce104 "short stories">]>

### ISSUE THREAD

**Issue by YaEvan** [senny/sablon#65]
when i using your test code in test/sablon_test.rb:
 I simplified the code， 

`@base_path = Pathname.new(File.expand_path("~/Downloads/sablon_test"))`

`template = Sablon.template(@base_path+"html_temp.docx")`

`context = {article: Sablon.content(:html, "I am fond of writing <i>short stories</i> and <i>poems</i> in my spare time,  <br />and have won several literary contests in pursuit of my <b>passion</b>.")}`

`template.render_to_file((@base_path+"html2.docx"), context)`

ArgumentError: Don't know how to handle node: #<Nokogiri::XML::Element:0x3fc5e96cf3d8 name="i" children=[#<Nokogiri::XML::Text:0x3fc5e96ce104 "short stories">]>

**Comment by senny** [comment]
@YaEvan hi, thanks for reporting.

Could you try to wrap the HTML in a container tag like a `<div>` or a `<p>`?

**Comment by YaEvan** [comment]
@senny thank you for your reply，i have tried <p>,<div> ...tags in the Usage, no problem. just for the <i> is error. 
First of all, thanks for your gem, but i have a question, how can i add pictures to docx? :)

**Comment by YaEvan** [comment]
@senny i also found the `<br>,<b>`had the same problem.

**Comment by senny** [comment]
@stadelmanma any thoughts? I'm pretty sure that `i` tags were covered.

@YaEvan there's no current way to add images. See #6 and #54

**Comment by YaEvan** [comment]
@senny  thanks, i got you. i hope you can find the right solution at an early date.  :)

**Comment by stadelmanma** [comment]
@YaEvan All inline tags (`<i>`, `<br>`, `<span>`, etc.) need to be nested inside `<p>` or `<div>`. 

An example of correct HTML syntax is below:
```HTML
<p>
    Some regular text, <i>some italicized text</i>.
    <br />
    Some more text.
</p>
``` 

When inline tags exist outside of a `<div>` or `<p>` you'll get that error, which happens to be the same error if you use an unsupported tag. @senny perhaps we should try and adjust the error message to be more informative?

**Comment by YaEvan** [comment]
@stadelmanma thanks for your answer. this is really useful.If so, i think this condition should be written in the manual or provide a more friendly error message. :)
