### ISSUE TITLE
Support for Non-mailmerge fields?

### ISSUE THREAD

**Issue by TheBerg** [senny/sablon#7]
So, as we are investigating using this library we are finding that creating mail merge fields are a PITA. Dang Microsoft.

I imagine our customers editing the text of the merge fields rather than the merge field, which would result in XML like:

```
            <w:r>
              <w:instrText xml:space="preserve">MERGEFIELD =email.address \* MERGEFORMAT </w:instrText>
            </w:r>
            <w:r>
              <w:fldChar w:fldCharType="separate"/>
            </w:r>
            <w:r>
              <w:rPr>
                <w:noProof/>
              </w:rPr>
              <w:t>«=email.type»</w:t>
            </w:r>
            <w:r>
              <w:fldChar w:fldCharType="end"/>
            </w:r>
```
In this you can see the merge field specified is `email.address` but the one visible in the word document is `email.type`. I am wonderif if we should make it so that allowing the use "fake" merge fields would be a good idea. i.e. `{{email.type}}` or `<<email.type>>`

Thoughts?

**Comment by senny** [comment]
@TheBerg any thoughts?

**Comment by TheBerg** [comment]
@senny We decided to postpone this feature in our app because of some of the weirdness of how MailMerge labels work in MS Word. When we get back we plan on trying to add text markers to this project, we just didn't have the time to do that. In the meantime we are using liquid & wkhtmltopdf to get the same results, just makes it harder for our end users to be able to make changes.

**Comment by senny** [comment]
Thank you for the heads up, I'm going to close this for now. Feel free to ping me again if you have questions.

**Comment by 7imon7ays** [comment]
I'm thinking of monkeypatching Sablon to specify my own text markers. My project is ok treating edge cases like spell-check as unspecified behavior.

Does that sound do-able? I'm guessing I'll need to change the `KEY_PATTERN` in [mail_merge.rb](https://github.com/senny/sablon/blob/bb3c81ef5411b76a5514f844f03c35932965d120/lib/sablon/parser/mail_merge.rb) and edit the [field handlers](https://github.com/senny/sablon/blob/bb3c81ef5411b76a5514f844f03c35932965d120/lib/sablon/processor/document/field_handlers.rb).

Let me know if you think this is crazy. Or if it sounds useful I can post a snippet if / when I get working code, in case more folks want to experiment with this.

**Comment by stadelmanma** [comment]
Hi @7imon7ays I'm not sure I understand what you are trying to accomplish, changing the `KEY_PATTERN` may be sufficient if you are still looking for mail merge fields. If you are looking for a different XML node then more logic will need changed.

**Comment by 7imon7ays** [comment]
Yes I was hoping to use something other than mail merge fields because Google Docs doesn't support those. But if it requires too much of a hack I'll try another solution first.

**Comment by gmhawash** [comment]
Hi @7imon7ays  Have you made any progress on using different merge markers?

**Comment by 7imon7ays** [comment]
Hi @gmhawash, sadly I ended up processing xml strings directly. Can't say it was the most fun to code but I couldn't avoid using Google Docs and Docs doesn't support mail merge fields. I think my team also considered using the Google Docs API but for some reason that didn't cut it. I can't remember why. Good luck!
