### ISSUE TITLE
Dropping the Gemfile.lock from version control

### ISSUE THREAD

**Issue by stadelmanma** [senny/sablon#75]
@senny I was going through and updating our dependencies and that got me thinking since this is a gem should we drop the Gemfile.lock from version control? 

According to these links we shouldn't have a Gemfile.lock for ruby gems: 
http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
https://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore

Their logic makes sense, let me know what you think.

**Comment by senny** [comment]
I don't like removing `Gemfile.lock` from source control. While it's true that it does not extent to endusers, removing it does not guarantee that either. In realty, there will be a big mix of version combinations out there. I do prefer to check Gemfile.lock into source control to ensure that every contributor has a stable environment. If one wants to address the "latest dependencies should be compatible problem", CI is the right tool for this. A separate build can remove the `Gemfile.lock` and install latest gems before running tests.

Note that we use the same practices on the Rails team (https://github.com/rails/rails/blob/master/Gemfile.lock)

I hope this makes sense. Let me know if anything is not clear or if you have further questions.

**Comment by stadelmanma** [comment]
Sounds good to me 👍
