### ISSUE TITLE
couldn't handle span tag 

### ISSUE THREAD

**Issue by ahmedelmahalawey** [senny/sablon#77]
Hi Everybody

It says in the documentation that the span tag is handled but when I try this html `Sablon.content(:html,'<div>King <span><</span> Kong </div>' )` it generates this error 

> Don't know how to handle node: #<Nokogiri::XML::Element:0x3fd38d7544f0 name="span" children=[#<Nokogiri::XML::Text:0x3fd38dae1f14 "<">]>

So what am I doing wrong here, I am currently using Sablon 0.0.21

**Comment by stadelmanma** [comment]
@senny I think we need to tag a new release and push it to ruby gems. I don't believe I have the permissions to do that.

**Comment by senny** [comment]
@stadelmanma I'm currently on vacation and traveling. My internet connection is mostly poor. I'll try to cut a release soon or grant permissions to you.

**Comment by senny** [comment]
Released with `0.0.22`
