### ISSUE TITLE
Test against ruby 2.4.2

### ISSUE THREAD

**Issue by siegy22** [senny/sablon#78]
Hey @stadelmanma 

Right now, travis-ci builds with `2.4.1` if we put `2.4` in our `.travis.yml`.
https://travis-ci.org/senny/sablon/jobs/306055382

We may want to really test against 2.4.2 and not 2.4.1.

This issue is just to keep track of that because I just noticed that by accident, I'll do it myself

**Comment by stadelmanma** [comment]
Hi @siegy22 if sablon integrated with Ruby at a low level or had a lot of core extensions (like Rails) I would agree. However, we work at a pretty high level at least for now so I don't think there is any harm in letting Travis lag behind a patch version. If we notice it starts lagging behind kind of far then we can edit the config accordingly.

Thanks for bringing this up!

**Comment by senny** [comment]
I second the stance of @stadelmanma. No need for a library like this to force a patch-level of Ruby unless there are essential dependencies that need it or benefit from it.
