### ISSUE TITLE
Exporting an a Tag with & character in the href the exported file is corrupted

### ISSUE THREAD

**Issue by ahmedelmahalawey** [senny/sablon#94]
When the href value of a Tag contains special characters like ampersand, the exported file is corrupted. After investigating I found out that the Relationship tag and its attributes get lowercased when added to the @relationships object. 
 
for example:

html text = "https://www.google.com.eg/?gfe_rd=cr&dcr=0&ei=mSKcWqXgIIKZX9zomrAL"

exported xml node = `<relationship type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" target="https://www.google.com.eg/?gfe_rd=cr&amp;dcr=0&amp;ei=WAGcWsyWCbKZX-nZAg" targetmode="External" id="rId15">`

expected exported xml node = `<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://www.google.com.eg/?gfe_rd=cr&amp;dcr=0&amp;ei=WAGcWsyWCbKZX-nZAg" TargetMode="External" Id="rId15">`

**Comment by stadelmanma** [comment]
This appears to be a noted issue with Nokogiri when there isn't a DOCTYPE (which MS Word docs lack) https://github.com/sparklemotion/nokogiri/issues/961. I think the easy fix is simply gsubing the `&` with `&amp;` because thats all MS Word appears to do.

**Comment by amrfaisal** [comment]
@stadelmanma : Even if we send the original HTML with `&amp;` to Sablon, it gets transformed back to `&` at some place before reaching this line:
https://github.com/senny/sablon/blob/29c9f9f4176b22d8cf5c435c24f4918761138871/lib/sablon/document_object_model/relationships.rb#L104

**Comment by stadelmanma** [comment]
@amrfaisal can you test this against #95? I think that should fix things since I gsub the ampersand out during creation of the <Relationship> tag which is after the line in ast.rb you flagged. I also dropped a line on the relevant Nokogiri issue but given that it's been around since 2013 I doubt things will change.

**Comment by amrfaisal** [comment]
@stadelmanma : Tested and working as expected, thanks a lot for the quick fix, please notify me when this pull request got merged.

**Comment by stadelmanma** [comment]
@amrfaisal there is an update sablon release on ruby gems, 0.2.1, with this fix. Thanks for your help testing!

**Comment by amrfaisal** [comment]
That was fast, tested the new release, and it's working as expected. Thanks a lot.
